import {
  NPC_BRAIN_SCHEMA_VERSION,
  type CapabilityDefinition,
  type NpcBrainConfig,
} from './cognitiveModel.js';

const DEFAULT_CAPABILITIES: CapabilityDefinition[] = [
  ['think', 'Think', 'Evaluate context and prepare a decision'],
  ['perceive', 'Perceive', 'Read configured sensory and environment inputs'],
  ['plan', 'Plan', 'Build a short-horizon action plan'],
  ['speak', 'Speak', 'Generate and deliver dialogue'],
  ['follow', 'Follow', 'Maintain a configured distance from a target'],
  ['greet', 'Greet', 'Start a context-aware greeting'],
  ['patrol', 'Patrol', 'Traverse configured patrol points or areas'],
  ['use-object', 'Use Object', 'Interact with an allowed runtime object'],
  ['open-door', 'Open Door', 'Request an allowed door/open interaction'],
  ['sit', 'Sit / Use Point', 'Use an allowed seating or interaction point'],
  ['defend', 'Defend', 'Execute an allowed defensive response'],
  ['attack', 'Attack', 'Execute an allowed combat capability'],
  ['flee', 'Flee', 'Disengage and move toward a safe target'],
].map(([id, label, description]) => ({
  id,
  label,
  description,
  enabled: true,
  aiSelectable: true,
  cooldownMs: 0,
  requirements: [],
  targetConstraints: [],
  runtimeEvent: `npc.action.${id}`,
  parameters: {},
}));

export function createDefaultNpcBrainConfig(
  npcId = 'nova-showcase',
  now = new Date().toISOString(),
): NpcBrainConfig {
  return {
    schemaVersion: NPC_BRAIN_SCHEMA_VERSION,
    npcId,
    revision: 1,
    identity: {
      name: 'Nova',
      role: 'Engineer',
      selfConcept: 'A capable AI companion who solves practical problems and learns from experience.',
      background: 'A sci-fi systems engineer designed to assist, explore, communicate, and adapt.',
      worldview: 'Curiosity, competence, cooperation, and evidence are usually better than guessing.',
      tags: ['engineer', 'sci-fi', 'technology'],
    },
    model: {
      provider: 'OpenRouter',
      model: 'Auto / Best Available',
      temperature: 0.7,
      maxTokens: 4096,
    },
    reasoning: {
      strategy: 'balanced',
      reasoningDepth: 4,
      confidenceThreshold: 0.72,
      replanningIntervalMs: 600,
      contextBudgetTokens: 8192,
      fallback: 'ask',
      directives: [
        'Stay consistent with identity, memory, relationships, and current world state.',
        'Prefer actions exposed by the authoritative runtime capability catalog.',
        'Admit uncertainty when evidence is insufficient.',
      ],
    },
    psychology: {
      personality: {
        openness: 0.82,
        conscientiousness: 0.78,
        extraversion: 0.52,
        agreeableness: 0.72,
        emotionalStability: 0.76,
      },
      values: {
        loyalty: 0.76,
        honesty: 0.86,
        autonomy: 0.68,
        authority: 0.38,
        curiosity: 0.9,
        compassion: 0.72,
        achievement: 0.74,
        selfPreservation: 0.62,
      },
      drives: {
        safety: 0.58,
        belonging: 0.55,
        achievement: 0.71,
        exploration: 0.88,
        status: 0.28,
        protection: 0.66,
        purpose: 0.82,
      },
      baselineEmotion: {
        valence: 0.2,
        arousal: 0.36,
        joy: 0.52,
        trust: 0.68,
        fear: 0.12,
        anger: 0.08,
        sadness: 0.09,
        surprise: 0.31,
      },
      regulation: {
        stress: 0.16,
        patience: 0.74,
        impulsivity: 0.24,
        threatSensitivity: 0.46,
        recoveryRate: 0.72,
      },
    },
    memory: {
      workingMemoryItems: 16,
      retrievalLimit: 6,
      minimumImportanceToPersist: 0.58,
      decayEnabled: true,
      decayHalfLifeHours: 720,
      promoteWorkingToEpisodic: true,
      durableMemoryEnabled: false,
    },
    perception: {
      sightRadiusMeters: 18,
      fieldOfViewDegrees: 110,
      hearingSensitivity: 0.68,
      proximityMeters: 2.5,
      attentionIntervalMs: 250,
      trackDynamicObjects: true,
      trackStaticObjects: true,
    },
    knowledgeSources: [],
    voice: {
      provider: 'Browser TTS',
      speed: 1,
      pitch: 1,
      interruptible: true,
      subtitles: true,
    },
    capabilities: DEFAULT_CAPABILITIES.map((capability) => ({ ...capability })),
    integrations: {
      runtimeTarget: 'generic',
      aiPlaygroundEnabled: true,
      emitRuntimeEvents: true,
    },
    createdAt: now,
    updatedAt: now,
  };
}
